"""add state

Revision ID: 400e622802ad
Revises: 1caecedafdfe
Create Date: 2022-02-27 19:06:33.930309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400e622802ad'
down_revision = '1caecedafdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'state')
    # ### end Alembic commands ###
